# =============================================================================
# DistroZSH - ~/.zshrc launcher
# =============================================================================
#
# DistroZSH: a lightweight, framework-free, cross-distribution ZSH experience
# inspired by native Linux distributions.
#
# This file is a thin launcher. The engine lives in:
#
#   ~/.config/distrozsh/          (default $DISTROZSH_HOME)
#
# Do NOT edit this file. Put your personal settings in:
#
#   ~/.config/distrozsh/config.zsh
#
# =============================================================================

: "${DISTROZSH_HOME:=$HOME/.config/distrozsh}"

# DISTROZSH_HOME is intentionally left set: the prompt toggle (Ctrl+P) and
# theme/layout reloads read it at runtime.
if [[ -r "$DISTROZSH_HOME/init.zsh" ]]; then
    source "$DISTROZSH_HOME/init.zsh"
fi
